name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '25'
        distribution: 'temurin'
    
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    
    - name: Build with Gradle
      run: ./gradlew build
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and Push Quarkus Container Image
      run: |
        ./gradlew build \
          -Dquarkus.container-image.build=true \
          -Dquarkus.container-image.push=true \
          -Dquarkus.container-image.registry=ghcr.io \
          -Dquarkus.container-image.group=${{ github.repository_owner }} \
          -Dquarkus.container-image.name=${{ github.event.repository.name }} \
          -Dquarkus.container-image.tag=latest
    
    # - name: Publish test results
    #   if: always()
    #   uses: EnricoMi/publish-unit-test-result-action@v2
    #   with:
    #     files: '**/build/test-results/**/*.xml'
