name: Trigger auto deployment for validplate

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/validplate-AutoDeployTrigger-02a99dfd-2625-4737-b708-00b5d415a708.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.VALIDPLATE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.VALIDPLATE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.VALIDPLATE_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: ghcr.io
          registryUsername: ${{ secrets.VALIDPLATE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.VALIDPLATE_REGISTRY_PASSWORD }}
          containerAppName: validplate
          resourceGroup: validplate-demo
          imageToBuild: ghcr.io/validplate:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


